# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/coopernurse/gorp";
    fetch = {
      type = "git";
      url = "https://github.com/coopernurse/gorp";
      rev = "9cd2b5ef5b82fde4e7c51776ac3f94398b8af076";
      sha256 = "1iihvqfdmwc17ryw0kiciihd2ypccs2bfsmfcl8kjmqpyway506g";
    };
  }
  {
    goPackagePath = "github.com/gwitmond/eccentric-authentication";
    fetch = {
      type = "git";
      url = "https://github.com/gwitmond/eccentric-authentication";
      rev = "f8e3e6622e367e3a58d4fdaebc36d5dd3d21b40e";
      sha256 = "11djjx60r2jsrry8w7z32wwl0xshrm8r6mc3al9lswmc62gshl1n";
    };
  }
  {
    goPackagePath = "github.com/gwitmond/unbound";
    fetch = {
      type = "git";
      url = "https://github.com/gwitmond/unbound";
      rev = "b72ee60dd49eaff4a4f2c943a51682bc0814d592";
      sha256 = "1fwvalzkf1si5nkj429slhbz0zhva8qgadifb9s9h1m2frzh5bay";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "fba66eb11643069e747022997e9be3b502b2c6fb";
      sha256 = "1y6jsazbxz626r0afz2klqvzc94nbi7jwcgdknylk3cxqs0qd9gr";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "0e2717dc3cc05907dc23096ef3a9086ea93f567f";
      sha256 = "1ra8yrndlwp55i0013l5hx5b7mqibw2bjs1ilxa9pbwgdkb5zn4l";
    };
  }
]
